import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import StyledComponentsRegistry from '@/lib/styled.component.registry'
import { Providers } from '../StoreProvider'
import 'react-toastify/dist/ReactToastify.css';
import { LoaderDots } from '@/components/loader'
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <head>
          <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'></link>
        </head>
        <body className={inter.className}>
          <StyledComponentsRegistry>
            <Suspense fallback={<LoaderDots height="100vh" />}>
              {children}
            </Suspense>
          </StyledComponentsRegistry>
        </body>
      </html>
    </Providers>
  );
}
