import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import StyledComponentsRegistry from '@/lib/styled.component.registry'
import { Providers } from '../StoreProvider'
import { cookies } from 'next/headers'
import { getIronSession, SessionData } from 'iron-session'
import { sessionOptions, User } from '@/lib/session'
import Layout from '@/components/layout'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getIronSession<SessionData>(cookies(), sessionOptions)

    return (
        <Providers>
            <html lang="en">
                <head>
                    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'></link>
                </head>
                <body className={inter.className}>
                    <StyledComponentsRegistry>
                        <Layout>
                            {children}
                        </Layout>
                    </StyledComponentsRegistry>
                </body>
            </html>
        </Providers>
    );
}
